name: Build Setup
description: Setup for standard Java builds

runs:
  using: 'composite'

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        add-job-summary: 'on-failure'
        gradle-home-cache-includes: |
          caches
          caches/retro_futura_gradle
          notifications
          jdks
          wrapper