name: Publish to Modrinth

on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true

env:
  CHANGELOG_LOCATION: "Changelog is available [here](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }})"
  RELEASE_TYPE: 'beta'

jobs:
  mr-release:
    name: Release to Modrinth
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Grant Permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - uses: actions/download-artifact@v4
        with:
          path: build/libs
          merge-multiple: true

      - name: Publish to Modrinth
        env:
          MODRINTH_API_KEY: "${{ secrets.MODRINTH_API_KEY }}"
          MODRINTH_PROJECT_ID: "${{ secrets.MODRINTH_PROJECT_ID }}"
          CHANGELOG_LOCATION: "${{ env.CHANGELOG_LOCATION }}"
          RELEASE_TYPE: "${{ env.RELEASE_TYPE }}"
        run: ./gradlew modrinth --warning-mode all --build-cache