name: Publish Betas to GitHub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # any SemVer tag, e.g. v1.2.3

env:
  # type of release
  RELEASE_TYPE: 'beta'

concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to create GitHub releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Grant Permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build --warning-mode all

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "build/libs/*.jar"
          generate_release_notes: true
          fail_on_unmatched_files: true