name: Publish To Github
on:
  workflow_call:
    inputs:
      release_tag:
        type: string
        required: true

jobs:
  gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: temp
          merge-multiple: true

      - run: echo "tag=${{ inputs.release_tag }}"

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          files: temp/*.jar
          generate_release_notes: true
          fail_on_unmatched_files: true
