name: Spotless Formatting Check

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
  pull_request:

concurrency:
  group: formatting-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    name: Spotless Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Grant Permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run Spotless Formatting Check with Gradle
        run: ./gradlew spotlessCheck --warning-mode all